CREATE DATABASE pizza_sales;
use pizza_sales;

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    date DATE,
    time TIME
);

CREATE TABLE pizza_types (
    pizza_type_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100),
    category VARCHAR(50),
    ingredients TEXT
);

CREATE TABLE order_details (
    order_details_id INT PRIMARY KEY,
    order_id INT,
    pizza_id VARCHAR(50),
    quantity INT,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (pizza_id)
    REFERENCES pizzas(pizza_id)
);

CREATE TABLE pizzas (
    pizza_id VARCHAR(50) PRIMARY KEY,
    pizza_type_id VARCHAR(50),
    size VARCHAR(5),
    price DECIMAL(5,2),

    FOREIGN KEY (pizza_type_id)
    REFERENCES pizza_types(pizza_type_id)
);

SELECT COUNT(*) FROM orders;
SELECT COUNT(*) FROM pizzas;
SELECT COUNT(*) FROM pizza_types;

-- 1.What is the total revenue generated by the pizza store?
SELECT
ROUND(SUM(od.quantity*p.price),2) AS total_revenue
FROM order_details od
JOIN pizzas p ON 
od.pizza_id=p.pizza_id;

-- 2.Total number of orders
SELECT COUNT(DISTINCT order_id) as total_orders
FROM order_details;

-- 3.TOTAL pizzas sold
SELECT 
SUM(quantity) as total_pizzas
FROM order_details;

-- 4.average order value
SELECT ROUND(SUM(od.quantity*p.price)/COUNT(DISTINCT order_id)) AS average_order_value
FROM order_details od
JOIN pizzas p ON 
p.pizza_id=od.pizza_id;

-- 5.Most exprensive pizza
SELECT pt.name,p.price 
FROM pizzas p
JOIN pizza_types pt ON 
p.pizza_type_id=pt.pizza_type_id
ORDER BY 2 DESC LIMIT 1
;

-- 6.Least Expensive Pizza
SELECT pt.name,p.price 
FROM pizzas p
JOIN pizza_types pt ON 
p.pizza_type_id=pt.pizza_type_id
ORDER BY 2 ASC LIMIT 1
;

-- 7.which pizza was ordered the most
SELECT pt.name,SUM(od.quantity) AS total_orders
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

-- 8.which pizza was ordered the least
SELECT pt.name,SUM(od.quantity) AS total_orders
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY 1
ORDER BY 2 ASC
LIMIT 1;

-- 9.Revenue by Category
SELECT pt.category,SUM(od.quantity*p.price) AS total_revenue
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY pt.category
ORDER BY 2;

-- 10.revenue  by size
SELECT p.size,SUM(od.quantity*p.price) AS total_revenue
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
GROUP BY p.size
ORDER BY 2 DESC;
 
 -- 11.Peak Order Hour
SELECT 
    EXTRACT(HOUR FROM time) AS order_hours,
    COUNT(order_id) AS orders
FROM orders
GROUP BY order_hours
ORDER BY orders DESC
LIMIT 1;

-- 12.Busiest Day
SELECT 
date AS day_no,
COUNT(order_id) AS total_orders
FROM orders
GROUP BY day_no 
ORDER BY total_orders DESC
LIMIT 1;

-- 13.Monthly ORDER Trend
SELECT 
MONTHNAME(date) AS month_name,
COUNT(order_id) AS total_orders
FROM orders
GROUP BY month_name
ORDER BY  total_orders DESC
LIMIT 1;


 -- 14.Monthly revenue Trend
SELECT MONTHNAME(date) as month_name,ROUND(SUM(od.quantity*p.price)) as total_revenue
FROM order_details od
JOIN pizzas p ON 
od.pizza_id=p.pizza_id
Join orders o ON
od.order_id=o.order_id
GROUP BY month_name
ORDER BY total_revenue DESC;

-- 15.Daily Order Trend
SELECT 
date AS date_no,
COUNT(order_id) AS total_orders
FROM orders
GROUP BY date_no
ORDER BY  date_no ;

-- 16.Top 5 Revenue Generating Pizzas
SELECT pt.name,ROUND(SUM(od.quantity*p.price))  as total_revenue
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY pt.name
ORDER BY total_revenue DESC
LIMIT 5;

-- 17.Bottom 5 Revenue Generating Pizzas
 SELECT pt.name,ROUND(SUM(od.quantity*p.price))  as total_revenue
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY pt.name
ORDER BY total_revenue ASC
LIMIT 5;

-- 18.Average Pizzas Per Order
SELECT ROUND(SUM(quantity)/COUNT(DISTINCT order_id),2) AS average_pizza_per_order
FROM order_details;

-- 19.Orders with More Than 3 Pizzas
SELECT order_id,SUM(quantity) AS total_pizzas FROM order_details
GROUP BY order_id
HAVING total_pizzas>3;

-- 20.Category-wise Quantity Sold
SELECT pt.category,ROUND(SUM(od.quantity))  as quantity_sold
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY pt.category
ORDER BY quantity_sold;

-- 21.Sales by Time of Day
SELECT
CASE
WHEN HOUR(time)<12 THEN 'Morning'
WHEN HOUR(time) BETWEEN 12 AND 17 THEN 'Afternoon'
ELSE 'Evening'
END AS time_of_day,
COUNT(order_id) as total_orders
FROM orders
GROUP BY time_of_day
ORDER BY total_orders DESC
;

-- 22.running revenue
SELECT o.date,SUM(od.quantity*p.price) AS total_revenue,
SUM(
SUM(od.quantity*p.price))
OVER(ORDER BY o.date) AS running_revenue
FROM order_details od
JOIN pizzas p ON 
od.pizza_id=p.pizza_id
JOIN orders o ON
od.order_id=o.order_id
GROUP BY o.date;

-- 23.rank pizzas by revenue
SELECT pt.name,SUM(od.quantity*p.price) AS total_revenue,
RANK() OVER (ORDER BY SUM(od.quantity*p.price) DESC) AS pizza_rank
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY pt.name;

-- 24.Top Pizza in Each Category
WITH ranked_pizzas AS(
SELECT pt.name,pt.category,SUM(od.quantity*p.price) AS total_revenue,
RANK() OVER (partition by  pt.category ORDER BY SUM(od.quantity*p.price) DESC) AS pizza_rank
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY pt.category,pt.name
)
SELECT * FROM ranked_pizzas
WHERE pizza_rank=1 ;

-- 25.Revenue Contribution Percentage
SELECT pt.category,ROUND(SUM(od.quantity*p.price)) AS total_revenue,

ROUND((SUM(od.quantity*p.price)/
(SELECT (SUM(od2.quantity*p2.price)) FROM
order_details od2 JOIN pizzas p2 ON
od2.pizza_id=p2.pizza_id))*100) AS total_percentage
FROM order_details od 
JOIN pizzas p ON 
od.pizza_id=p.pizza_id
JOIN pizza_types pt ON
p.pizza_type_id=pt.pizza_type_id
GROUP BY pt.category
ORDER BY total_revenue;

-- 26. Top 3 Pizzas Per Category
WITH ranked_pizzas AS(
SELECT pt.name,pt.category,SUM(od.quantity*p.price) AS total_revenue,
RANK() OVER (partition by  pt.category ORDER BY SUM(od.quantity*p.price) DESC) AS pizza_rank
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY pt.category,pt.name
)
SELECT * FROM ranked_pizzas
WHERE pizza_rank<=3 ;

-- 27. Hourly Revenue Analysis
SELECT 
    EXTRACT(HOUR FROM time) AS order_hours,
    COUNT(order_id) AS orders
FROM orders
GROUP BY order_hours
ORDER BY orders DESC
LIMIT 1;

-- 28.hourly revenue analysis
SELECT
HOUR(o.time) AS order_hour,
ROUND(SUM(od.quantity * p.price),2) AS revenue
FROM order_details od
 JOIN orders o ON
o.order_id = od.order_id
JOIN pizzas p ON od.pizza_id=p.pizza_id
GROUP BY order_hour
ORDER BY revenue DESC;

--  29.Category Performance Ranking
SELECT pt.category,SUM(od.quantity*p.price) AS total_revenue,
RANK() OVER ( ORDER BY SUM(od.quantity*p.price) DESC) AS category_rank
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY pt.category
ORDER BY category_rank ASC;

-- 30.Pizza Sales Segmentation
SELECT pt.name,pt.category,SUM(od.quantity*p.price) AS total_revenue,
CASE
WHEN SUM(od.quantity * p.price) > 30000 THEN 'High Performing'
WHEN SUM(od.quantity * p.price) BETWEEN 15000 AND 30000 THEN 'Medium Performing'
ELSE 'Low Performing'END AS performance_segment
FROM order_details od
Join pizzas p ON 
od.pizza_id=p.pizza_id
join pizza_types pt ON
pt.pizza_type_id=p.pizza_type_id
GROUP BY pt.name,pt.category
ORDER BY performance_segment ASC;

-- 31.moving average analysis
WITH daily_sales AS(
SELECT o.date,SUM(od.quantity*p.price) AS total_revenue
FROM order_details od
JOIN orders o ON
o.order_id=od.order_id
Join pizzas p ON 
od.pizza_id=p.pizza_id GROUP BY o.date )
SELECT date,total_revenue,AVG(total_revenue) OVER(ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS moving_avg FROM daily_sales;

-- 32.Revenue Growth Rate
WITH monthly_sales AS(
SELECT  MONTH(o.date) AS month_no,MONTHNAME(o.date) AS month_name,SUM(od.quantity*p.price) AS total_revenue
FROM order_details od
JOIN orders o ON
o.order_id=od.order_id
Join pizzas p ON 
od.pizza_id=p.pizza_id GROUP BY month_name,month_no )
SELECT month_no,month_name,total_revenue,
LAG(total_revenue ) OVER (ORDER BY  month_no ) AS previous_month_sales,

ROUND((total_revenue -LAG(total_revenue) OVER(ORDER BY month_no))
/LAG(total_revenue) OVER(ORDER BY month_no)* 100,2) 
AS growth_percentage
 FROM monthly_sales ;
